# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
# samples: 20180831_lambda_kappa.samples.tsv
# samples: "/farmshare/user_data/gday/mayo/data/CoMMpass/CoMMpass_clin_info.csv"
samples: "CoMMpass_clin_WXS_avail.csv"

ig_bed: "/farmshare/user_data/gday/mayo/data/reference/ig_large_regions.bed"
# ig_bed: Ig_exons.sorted.extended300.merged.bed

igblast:
  germline_db_V: "/farmshare/user_data/gday/mayo/data/imgt/IG_V.ncbi.fasta"
  germline_db_J: "/farmshare/user_data/gday/mayo/data/imgt/IG_J.ncbi.fasta"
  germline_db_D: "/farmshare/user_data/gday/mayo/data/imgt/IG_D.ncbi.fasta"
  auxiliary_file: "/farmshare/user_data/gday/mayo/software/ncbi-igblast-1.9.0/optional_file/human_gl.aux"

assembly:
  min_frac_to_assemble: 0.01 
  min_reads: 10
  max_clones_to_assemble: 5
  
sra_dir: "/farmshare/user_data/gday/mayo/data/CoMMpass-sra/"
sra_table: "/farmshare/user_data/gday/mayo/data/CoMMpass/20181105_SraRunTable.txt"

genomic_source: True
