# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
# samples: 20180831_lambda_kappa.samples.tsv
samples: "20181110_CoMMpass_prelim.tsv"

ig_bed: "/farmshare/user_data/gday/mayo/data/reference/ig_large_regions.bed"
# ig_bed: Ig_exons.sorted.extended300.merged.bed

igblast:
  germline_db_V: "/farmshare/user_data/gday/mayo/data/imgt/IG_V.ncbi.fasta"
  germline_db_J: "/farmshare/user_data/gday/mayo/data/imgt/IG_J.ncbi.fasta"
  germline_db_D: "/farmshare/user_data/gday/mayo/data/imgt/IG_D.ncbi.fasta"
  auxiliary_file: "/farmshare/user_data/gday/mayo/software/ncbi-igblast-1.9.0/optional_file/human_gl.aux"



