Bootstrap: docker
From: linuxbrew/linuxbrew


%setup
  brew install samtools
  
  brew tap milaboratory/all
  brew install mixcr

  brew tap brewsci/bio
  brew tap brewsci/science
  brew install VelvetOptimiser