Bootstrap: docker
From: linuxbrew/linuxbrew


%setup
  #sudo apt-get install build-essential curl file git
  
  exec brew tap milaboratory/all
  exec brew install mixcr

  exec brew tap brewsci/bio
  exec brew tap brewsci/science
  exec brew install VelvetOptimiser