$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
  samples:
    type: string
  clones_file:
    type: string
  stats_file:
    type: string
  ig_bed:
    type: string
required:
  - samples
  - ig_bed